version: "3.9"

services:
  gym-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gym-tracker-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "gym-tracker"
